AllCops:
  TargetRubyVersion: 2.6
  Rails:
    Enabled: true
  Exclude:
    - 'git/**/*'
    - 'bin/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'lib/**/*'
    - 'log/**/*'
    - 'node-modules/**/*'
    - 'public/**/*'
    - 'storage/**/*'
    - 'test/**/*'
    - 'tmp/**/*'
    - 'vendor/*'
    - 'Gemfile'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Documentation:
  Enabled: false