AllCops:
  Exclude:
    - 'git/**/*'
    - 'bin/*'
    - 'db/**/*'
    - 'lib/**/*'
    - 'log/**/*'
    - 'node-modules/**/*'
    - 'public/**/*'
    - 'storage/**/*'
    - 'test/**/*'
    - 'tmp/**/*'
    - 'vendor/*'
